persistence:
  enabled: true
  size: 5Gi

service:
  type: NodePort
  nodePort: 30100

nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
  - key: "key"
    operator: "Equal"
    value: "master"
    effect: "NoSchedule"

