version: "3.7"

services:
 
  timescale:
    image: timescale/timescaledb:2.0.1-pg12
    container_name: timescale
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2vTv2rNxQteHjMjQY6iAxxl2MgCEu4hm
    volumes:
      - ./postgresql:/var/lib/postgresql/data
 