---
- name: Build a cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become_for_all: true
  roles:
    - role: xanmanning.k3s

- hosts: db-servers
  roles:
    - role: geerlingguy.nfs

- hosts: k3s_cluster 
  tasks:
  - name: copy 
    copy:
      dest: "/var/lib/rancher/k3s/server/manifests/nfs.yml"
      src: "./nfs.yml"
  - name: replace nfs ip
    ansible.builtin.replace:
      path: /var/lib/rancher/k3s/server/manifests/nfs.yml
      regexp: "x.x.x.x"
      replace: "{{hostvars['db-servers']['ansible_default_ipv4']['address']}}"
