- hosts: all
  tasks:
    - name: Install a list of packages
      become: true
      apt:
        pkg:
          - vim
          - htop
          - screen
          - trash-cli
    - name: clone configs
      become: yes
      git:
        repo: https://github.com/ASC689561/k8s-config.git
        dest: /home/configs
    - name: line insert
      lineinfile:
        path: .zshrc
        line: "source /home/configs/ansible/aliases"
        insertbefore: BOF
  roles:
    - { role: vaulttec.zsh, zsh_ohmy_theme: robbyrussell, zsh_ohmy_plugins: [git, docker, docker-compose, kubectl], }
    # - { role: geerlingguy.docker, docker_service_state: started, docker_service_enabled: true, docker_restart_handler_state: restarted, docker_install_compose: false, become: yes, }
- hosts: all
  become: true
  tasks:
    - name: line insert
      lineinfile:
        path: .zshrc
        line: "source /home/configs/ansible/aliases"
        insertbefore: BOF
  roles:
    - { role: vaulttec.zsh, zsh_ohmy_theme: robbyrussell, zsh_ohmy_plugins: [git, docker, docker-compose, kubectl], }
