#!/usr/bin/env bash
if [ `cat /proc/sys/kernel/hostname` = "t520" ]
then
	xmodmap -e "keycode 166 = Home"
	xmodmap -e "keycode 167 = End"
fi

export HISTCONTROL=ignoredups

alias hisg='history | grep '

alias pu='pushd . && cd '
alias po='popd'
alias rm='sudo trash -rf'
alias vm='docker run -it --rm asc686f61/python_alpine:v1.0 bash'

ren(){
  for f in *.$1; do
    mv -- "$f" "${f%.$1}.$2"
  done
}

qr(){
	qrencode -o - "$1" | display
}

backup () {
    for file in "$@"; do
        local new=${file}_$(date '+%Y-%m-%d_%H-%M-%S')
        while [[ -f $new ]]; do
            new+="~";
        done;
        printf "copying '%s' to '%s'\n" "$file" "$new";
        cp -ipr "$file" "$new";
	zip -rm "$new".zip "$new";
	du -sh "$new".zip
    done
}

alias dc-stop-all='sudo docker stop $(sudo docker ps -aq)'
alias dc-ps='sudo docker ps'
alias dc-rm-all='sudo docker rm $(sudo docker ps -aq)'
alias dc-rm-exited='sudo docker ps -a | grep Exit | cut -d " " -f 1 | xargs sudo docker rm'
alias dc-rmi-none='sudo docker rmi $(sudo docker images -f "dangling=true" -q)'
alias dc-rmi-all='sudo docker rmi $(sudo docker images -aq)'
alias dc-rmi-5='docker rmi $(docker images -q | tail -n +5)'


alias tarc='tar -czvf '
alias tarx='tar -k -xzvf '
alias pip3='sudo python3 -m pip '
alias kcn='kubectl config set-context $(kubectl config current-context) --namespace '
alias chmodall='sudo chmod -R 777 '